### PR TITLE
Onboarding checklist

### PR DESCRIPTION
**Pull request by jen-dfci**
Added onboarding checklist to Information for New Centers.  2 changes from google doc:
1.  Added Step 8: Attend DCC Information Sessions (and changed some wording to flow into next section)
2.  For Step 7: Added language from Lisa Pasquale re: only HTAN PIs and Admins can fill out the HTAN Master Contact Form.

### CODE REVIEW

**Review by ecerami — CHANGES_REQUESTED** [review]
thanks!  Looks great.  I only noticed two things.

1. This paragraph had a strange character at the end:

image

2.  Not sure if this is on purpose, but the HTAN Master Contact Form is not linked.

**Comment by ecerami** [comment]
Also, noticed one more thing, related to missing spacing.

image

**Comment by jen-dfci** [comment]
@ecerami Thank you for catching those..extra character, spacing issue fixed and added HTAN Contact Form link.

**Comment by ecerami** [comment]
Thanks, looks good.

**Review by ecerami — APPROVED** [review]

**Pull request merged**
