### PR TITLE
Update Information for New Centers page

### PR DESCRIPTION
**Pull request by adamjtaylor**
Hey @jen-dfci, following some conversation with Lisa Pasquale in Sage Governence, we need to make the following changes to the Information from New Centers page.

This clarifies terminology used and removes the public link to the contact form as we only want PIs and Center Administrators to submit to this form - it should therefore only be shared by email or we can setup a Synapse link only usable by certain logged-in users.

### CODE REVIEW

**Review by jen-dfci — APPROVED** [review]

**Review by aclayton555 — CHANGES_REQUESTED** [review]
New line 42, "Please make sure to have a diussion with your data liason on this topic."

Fix typos to, "Please make sure to have a discussion with your data liaison on this topic."

**Comment by adamjtaylor** [comment]
Thank you @jen-dfci! I have a few more bits to implement and a conflict to resolve. Are you ok for me to merge when all done or shall I ping you for another review Monday morning?

**Comment by jen-dfci** [comment]
Go ahead and merge when done.  I'll make more edits Monday for the pdfs,
etc and, if I catch anything then, will add it to a new PR.

**Review by jen-dfci — APPROVED** [review]

**Review by aclayton555 — APPROVED** [review]

**Comment by aclayton555** [comment]
Thanks Adam and Jen. I think this is ready to merge!

**Pull request merged**
