### PR TITLE
Phase2 chgs

### PR DESCRIPTION
**Pull request by jen-dfci**

### CODE REVIEW

**Comment by ecerami** [comment]
Love the new dashboard page!

One small suggestion, on this page:  http://localhost:5000/data_submission/overview/, we have a link to the dashboard that goes to Linode directly.  Can we link to the new dashboard page instead?

**Comment by ecerami** [comment]
Next suggestion:  For Submitting Data Section, how about the following order, that follows the rough order of submitting data.

Introduction
Information for New HTAN Centers
HTAN Checklist for Acceptance of Data
Data Liaisons
Data De-Identification
What is Meta Data?
What is Index Date?
Submitting Assay Data and Metadata
Specific Assay/Data Element Details
HTAN Dashboard

**Comment by jen-dfci** [comment]
data submission link to hdash and page order changed. @ecerami would you be able to re-review?

**Comment by ecerami** [comment]
Looks great.  thanks!

**Review by ecerami — APPROVED** [review]
Looks great.  Approving...

**Pull request merged**
